stats.html
RickyMarin/CodeU-S19 pull request #10
Opened 2019-02-28 15:09 UTC by hedayaw

I made the html page that displays the number of messages.

2019-02-28 20:09 UTC, fatlotus commented on src/main/webapp/stats.html
> +            return response.json();S
```suggestion
            return response.json();
```

2019-02-28 21:06 UTC, RickyMarin requested changes
I'm not sure why the .gitignore file is there. Maybe git pull origin master to get the most recent code and then commit your code again?

2019-03-02 23:14 UTC, RickyMarin approved these changes

2019-03-02 23:16 UTC, RickyMarin commented
I re added a .gitignore to fix the merge conflict. I then committed the typo fix Jeremy suggested. The code itself looks good too, so no issues there.

2019-03-02 23:16 UTC, merged